export type CreativeFormat = {
  id: string;
  name: string;
  mediaType: 'static' | 'video' | 'carousel';
  description: string;
  bestFor: string[];
  bestWithArchetypes: string[];
  hookPlacement: string;
  copyLimitations: string[];
  requiredAssets: string[];
  avoid: string[];
};

export const CREATIVE_FORMATS: CreativeFormat[] = [
  { id: 'designed-static', name: 'Designed Static', mediaType: 'static', description: 'Polished feed graphic with deterministic text and brand styling.', bestFor: ['clarity','comparison','proof','positioning'], bestWithArchetypes: ['old-way-new-way','big-editorial-headline','comparison-chart','proof-first','one-big-benefit'], hookPlacement: 'Primary headline in top or center third.', copyLimitations: ['One main headline','Short support copy','One CTA'], requiredAssets: [], avoid: ['Dense body copy','Tiny text'] },
  { id: 'editorial-static', name: 'Editorial Static', mediaType: 'static', description: 'Magazine-like composition using strong typography and photography.', bestFor: ['founder-led brands','premium positioning','belief shifts'], bestWithArchetypes: ['big-editorial-headline','contrarian-belief','founder-confession','founder-story','magazine-editorial'], hookPlacement: 'Headline integrated with image composition.', copyLimitations: ['Headline-led','Minimal support text'], requiredAssets: ['photo recommended'], avoid: ['Generic stock-photo feel'] },
  { id: 'lofi-native-static', name: 'Lo-Fi Native Graphic', mediaType: 'static', description: 'Intentionally native, casual, platform-feeling image.', bestFor: ['trust','relatability','cold traffic'], bestWithArchetypes: ['notes-app','fake-search','fake-text-message','handwritten-annotation','meme-format'], hookPlacement: 'Native UI-like or handwritten focal point.', copyLimitations: ['Short conversational copy'], requiredAssets: [], avoid: ['Over-polishing'] },
  { id: 'notes-app', name: 'Notes App', mediaType: 'static', description: 'Notes-style text creative with highly scannable founder voice.', bestFor: ['confessions','lists','belief shifts'], bestWithArchetypes: ['founder-confession','three-mistakes','mini-framework','ugly-truth'], hookPlacement: 'First line of note.', copyLimitations: ['Must read like a real note','No design-spec labels'], requiredAssets: [], avoid: ['Long paragraphs'] },
  { id: 'fake-text-dm', name: 'Fake Text / DM', mediaType: 'static', description: 'Conversation-style static that dramatizes a customer truth.', bestFor: ['objections','micro-moments','social proof framing'], bestWithArchetypes: ['fake-text-message','micro-moment','objection-crusher'], hookPlacement: 'First message bubble.', copyLimitations: ['2-5 bubbles','Natural phrasing'], requiredAssets: [], avoid: ['Invented testimonials'] },
  { id: 'annotated-screenshot', name: 'Annotated Screenshot', mediaType: 'static', description: 'Real screenshot with callouts and annotations.', bestFor: ['SaaS','proof','feature education'], bestWithArchetypes: ['annotated-screenshot','how-it-works','feature-to-benefit','proof-first','result-dashboard'], hookPlacement: 'External headline or one annotation.', copyLimitations: ['Annotations must be brief'], requiredAssets: ['screenshot'], avoid: ['Unreadable UI'] },
  { id: 'ugc-photo-overlay', name: 'UGC Photo + Overlay', mediaType: 'static', description: 'Founder/customer-style photo with direct-response overlay.', bestFor: ['trust','founder-led offers','identity'], bestWithArchetypes: ['identity-callout','this-is-for-you-if','founder-confession','aspirational-outcome'], hookPlacement: 'Text-safe area opposite face.', copyLimitations: ['One hook','Optional support line'], requiredAssets: ['photo'], avoid: ['Text over face'] },
  { id: 'talking-head', name: 'Talking Head', mediaType: 'video', description: 'Direct-to-camera founder or expert delivery.', bestFor: ['trust','education','objection handling','story'], bestWithArchetypes: ['founder-story','founder-confession','contrarian-belief','objection-crusher','three-mistakes'], hookPlacement: 'First spoken sentence and captions.', copyLimitations: ['Hook < 5 sec','One core idea'], requiredAssets: ['speaker'], avoid: ['Long intros'] },
  { id: 'broll-voiceover', name: 'B-Roll + Voiceover', mediaType: 'video', description: 'Visual sequence under a concise voiceover.', bestFor: ['aspiration','process','story','lifestyle'], bestWithArchetypes: ['before-after','timeline-process','aspirational-outcome','micro-moment'], hookPlacement: 'First VO line plus opening visual.', copyLimitations: ['Short captions','VO carries message'], requiredAssets: ['b-roll'], avoid: ['Unrelated generic footage'] },
  { id: 'screen-recording', name: 'Screen Recording', mediaType: 'video', description: 'Native product walkthrough focused on one useful outcome.', bestFor: ['SaaS','demo','mechanism'], bestWithArchetypes: ['how-it-works','feature-to-benefit','one-big-benefit','comparison-chart'], hookPlacement: 'Caption + immediate product action.', copyLimitations: ['One workflow per video'], requiredAssets: ['product access or recording'], avoid: ['Feature tours without outcome'] },
  { id: 'screen-recording-facecam', name: 'Screen Recording + Facecam', mediaType: 'video', description: 'Product demo with founder/creator trust layer.', bestFor: ['SaaS','education','founder-led software'], bestWithArchetypes: ['how-it-works','founder-story','feature-to-benefit'], hookPlacement: 'Spoken founder hook then demo.', copyLimitations: ['Keep facecam secondary during demo'], requiredAssets: ['speaker','screen recording'], avoid: ['Too many UI steps'] },
  { id: 'ugc-demo', name: 'UGC Demo', mediaType: 'video', description: 'Casual real-world demonstration of the product or process.', bestFor: ['ecommerce','apps','simple services'], bestWithArchetypes: ['problem-solution','how-it-works','product-in-context','feature-to-benefit'], hookPlacement: 'Problem or outcome in first shot.', copyLimitations: ['Conversational script'], requiredAssets: ['demo subject/product'], avoid: ['Over-scripted delivery'] },
  { id: 'founder-story-video', name: 'Founder Story Video', mediaType: 'video', description: 'Condensed founder-origin or realization story.', bestFor: ['trust','warm traffic','category creation'], bestWithArchetypes: ['founder-story','founder-confession','ugly-truth','contrarian-belief'], hookPlacement: 'Start at tension, not biography.', copyLimitations: ['30-75 seconds','One turning point'], requiredAssets: ['founder'], avoid: ['Chronological life story'] },
  { id: 'testimonial-video', name: 'Testimonial Video', mediaType: 'video', description: 'Real customer proof with clear outcome context.', bestFor: ['proof','warm traffic','objection reduction'], bestWithArchetypes: ['customer-quote','proof-first','objection-crusher'], hookPlacement: 'Strongest verified customer line.', copyLimitations: ['Use only supplied proof'], requiredAssets: ['real testimonial'], avoid: ['Invented or embellished claims'] },
  { id: 'carousel', name: 'Carousel', mediaType: 'carousel', description: 'Slide sequence that teaches or persuades one idea progressively.', bestFor: ['education','comparison','frameworks','belief shifts'], bestWithArchetypes: ['three-mistakes','mini-framework','comparison-chart','myth-vs-reality','old-way-new-way'], hookPlacement: 'Slide 1 headline.', copyLimitations: ['One idea per slide','Short body copy'], requiredAssets: [], avoid: ['Internal production labels','Paragraph-heavy slides'] },
  { id: 'before-after-carousel', name: 'Before / After Carousel', mediaType: 'carousel', description: 'Sequential transformation story.', bestFor: ['process','transformation','case studies'], bestWithArchetypes: ['before-after','old-way-new-way','timeline-process'], hookPlacement: 'Transformation tension on slide 1.', copyLimitations: ['Clear progression'], requiredAssets: [], avoid: ['Unverified results'] },
  { id: 'comparison-carousel', name: 'Comparison Carousel', mediaType: 'carousel', description: 'Progressive side-by-side contrast.', bestFor: ['differentiation','category positioning','objections'], bestWithArchetypes: ['comparison-chart','old-way-new-way','you-dont-need-x','myth-vs-reality'], hookPlacement: 'Unexpected contrast on slide 1.', copyLimitations: ['One contrast per slide'], requiredAssets: [], avoid: ['Feature dumping'] },
  { id: 'kinetic-typography', name: 'Kinetic Typography', mediaType: 'video', description: 'Motion-led text creative with minimal footage.', bestFor: ['strong hooks','belief shifts','quick concepts'], bestWithArchetypes: ['big-editorial-headline','contrarian-belief','curiosity-gap','question-led'], hookPlacement: 'First motion phrase.', copyLimitations: ['Very short text beats'], requiredAssets: [], avoid: ['Long sentences'] }
];

export const getFormat = (id: string) => CREATIVE_FORMATS.find((f) => f.id === id);
